$schema: https://schemas.meshmakers.cloud/construction-kit-compiled.schema.json
types:
- typeId: WasteMeter
  derivedFromCkTypeId: Basic-1.0.0/Asset-1.0.0
  attributes:
  - id: Environment-1.0.0/Weight-1.0.0
    name: Weight
  - id: Environment-1.0.0/TareWeight-1.0.0
    name: TareWeight
  - id: Environment-1.0.0/GrossWeight-1.0.0
    name: GrossWeight
associationRoles: []
attributes:
- id: GrossWeight
  valueType: Double
  metaData:
  - key: Unit
    value: t
  - key: Decimals
    value: 2
  - key: Type
    value: gross
- id: SampleAttribute1
  valueType: String
- id: TareWeight
  valueType: Double
  metaData:
  - key: Unit
    value: t
  - key: Decimals
    value: 2
  - key: Type
    value: tare
- id: Weight
  valueType: Double
  metaData:
  - key: Unit
    value: t
  - key: Decimals
    value: 2
  - key: Type
    value: net
records: []
enums: []
modelId: Environment
dependencies:
- Basic
