$schema: https://schemas.meshmakers.cloud/construction-kit-elements.schema.json
types:
  - typeId: Producer
    derivedFromCkTypeId: ${this}/MeteringPoint
    description: "A metering point identified as producer metering point"
    attributes:
      - id: ${this}/ProductionType
        name: ProductionType