name: $(MajorVersion).$(MinorVersion).$(date:yyMM).$(DayOfMonth)$(rev:rrr)-$(Build.SourceBranchName)

trigger:
  batch: true
  branches:
    include:
      - dev/*
      - main
  tags:
    exclude:
      - '*'
      
variables:
  - group: ApiKeys
  - group: OctoDefault
  - name: solutionFile
    value: 'Octo.ConstructionKit.sln'
  - name: artifactsFrameworkVersion
    value: 'net9.0'
  - name: buildConfiguration
    value: 'Release'
  - name: buildPlatform
    value: 'Any CPU'
  - name: isRelease
    value: ${{ startsWith(variables['Build.SourceBranch'], 'refs/tags/r') }}
  - name: isMain
    value: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}    

stages:
 - stage: Build
   jobs:
    - job: buildAndTest
      displayName: "Build nuget and execute tests"
      pool:
        name: Gerald-Local-Linux
      steps:
      - template: update-build-number.yml
      - checkout: self
        clean: true
        submodules: true
      - template: set-version.yml
      - task: DotNetCoreCLI@2
        displayName: 'Build'
        inputs:
          command: 'build'
          projects:  $(SolutionFile)
          arguments: '--configuration $(BuildConfiguration) /p:OctoNugetPrivateServer=$(nugetPrivateServer)'
          publishWebProjects: false
          zipAfterPublish: false
          modifyOutputPath: false
      - task: DotNetCoreCLI@2
        displayName: 'Test'
        inputs:
          command: 'test'
          projects: |
            '**/*Tests.csproj'
            !'**/*SystemTests.csproj'
          testRunTitle: 'CI'
      - template: handle-artifacts.yml
        parameters:
          constructionKitLibraryPaths:
            - 'src/Octo.Sdk.Demo/bin/$(buildConfiguration)/$(artifactsFrameworkVersion)/octo-ck-libraries/Octo.Sdk.Demo'          
            - 'src/Octo.Sdk.Packages.Basic/bin/$(buildConfiguration)/$(artifactsFrameworkVersion)/octo-ck-libraries/Octo.Sdk.Packages.Basic'          
            - 'src/Octo.Sdk.Packages.EnergyCommunity/bin/$(buildConfiguration)/$(artifactsFrameworkVersion)/octo-ck-libraries/Octo.Sdk.Packages.EnergyCommunity'          
            - 'src/Octo.Sdk.Packages.Environment/bin/$(buildConfiguration)/$(artifactsFrameworkVersion)/octo-ck-libraries/Octo.Sdk.Packages.Environment'          
            - 'src/Octo.Sdk.Packages.Industry.Basic/bin/$(buildConfiguration)/$(artifactsFrameworkVersion)/octo-ck-libraries/Octo.Sdk.Packages.Industry.Basic'          
            - 'src/Octo.Sdk.Packages.Industry.Energy/bin/$(buildConfiguration)/$(artifactsFrameworkVersion)/octo-ck-libraries/Octo.Sdk.Packages.Industry.Energy'          
            - 'src/Octo.Sdk.Packages.Industry.Fluid/bin/$(buildConfiguration)/$(artifactsFrameworkVersion)/octo-ck-libraries/Octo.Sdk.Packages.Industry.Fluid'          
            - 'src/Octo.Sdk.Packages.Industry.Maintenance/bin/$(buildConfiguration)/$(artifactsFrameworkVersion)/octo-ck-libraries/Octo.Sdk.Packages.Industry.Maintenance'          
      - template: push-nuget-package.yml           

