$schema: https://schemas.meshmakers.cloud/construction-kit-elements.schema.json
attributes:
  - id: EnergyProductionCapacity
    valueType: Double
    description: "Maximal energy production capacity in kWp"
  - id: ProductionType
    valueType: Enum
    valueCkEnumId: ${thisModel}/ProductionType