$schema: https://schemas.meshmakers.cloud/construction-kit-elements.schema.json
types:
  - typeId: EnvironmentalGoal
    derivedFromCkTypeId: ${Basic}/NamedEntity
    attributes:
      - id: ${this}/GoalText
        name: GoalText
      - id: ${this}/GoalState
        name: GoalStatus
    associations:
      - id: ${System}/ParentChild
        targetCkTypeId: ${Basic}/TreeNode