{
 "title": "Maintenance By Machine",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Site",
    "query": {}
   },
   {
    "name": "Line",
    "query": {}
   },
   {
    "name": "Machine",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Classification",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "$Machine", "type": "table" }
   ]
  },
  {
   "title": "Groups",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "$Machine", "type": "table" }
   ]
  },
  {
   "title": "States",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "$Machine", "type": "table" }
   ]
  },
  {
   "title": "Reactivated",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "meshmakersEquipmentMachineConnection.items.0.children.meshmakersAlarmConnection.items",
     "endTimePath": "endTime",
     "queryText": "query {\n  meshmakersEquipmentMachineConnection(rtId: \"$Machine\") {\n    items {\n      children {\n        meshmakersAlarmConnection(fieldFilter: [{attributeName:\"rtChangedDateTime\", operator: GREATER_THAN, comparisonValue:\"${__from:date:iso}\"}]) {\n          items {\n            reactivatedCount\n          }\n        }\n      }\n    }\n  }\n}\n"
    }
   ]
  },
  {
   "title": "Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Maintenance Events",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "meshmakersEquipmentMachineConnection.items.0.children.meshmakersAlarmConnection.items",
     "endTimePath": "endTime",
     "queryText": "query {\n  meshmakersEquipmentMachineConnection(rtId: \"$Machine\") {\n    items {\n      children {\n        meshmakersAlarmConnection(fieldFilter: [{attributeName:\"rtChangedDateTime\", operator: GREATER_THAN, comparisonValue:\"${__from:date:iso}\"}]) {\n          items {\n            message\n            state\n            receivedDateTime\n            clearedDateTime\n            reactivatedDateTime\n            acknowledgedDateTime\n            reactivatedCount\n            group\n            classification\n            alarmCause\n          }\n        }\n      }\n    }\n  }\n}\n",
     "timePath": "Time"
    }
   ]
  }
 ]
}