{
 "title": "Meshmakers Energy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Meter",
    "query": "SELECT distinct data['Designation'] FROM meshmakers_assets_meter LIMIT 50 "
   }
  ]
 },
 "panels": [
  { "title": "Einspeisung", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Min Einspeisung",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", data['ActivePower'] AS \"value\", data['Designation'] FROM meshmakers_assets_meter WHERE data['Designation'] = 'Netzbezug' AND $__timeFilter(timestamp) ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Max Einspeisung",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  MAX(data['ActivePower']) AS \"value\"\r\nFROM meshmakers_assets_meter\r\nWHERE data['Designation'] = 'Netzbezug' AND $__timeFilter(\"timestamp\")\r\nGROUP BY \"time\""
    }
   ]
  },
  { "title": "Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Min Consumption",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", data['ActivePower'] AS \"value\", data['Designation'] FROM meshmakers_assets_meter WHERE data['Designation'] = 'Gebäudeverbrauch' AND $__timeFilter(timestamp) ORDER BY timestamp ASC"
    }
   ]
  },
  {
   "title": "Max Consumption",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", data['ActivePower'] AS \"value\", data['Designation'] FROM meshmakers_assets_meter WHERE data['Designation'] = 'Gebäudeverbrauch' AND $__timeFilter(timestamp) ORDER BY timestamp ASC "
    }
   ]
  },
  { "title": "Live Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Meshmakers Gebäudeverbrauch",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", data['ActivePower'] AS \"value\", data['Designation'] FROM meshmakers_assets_meter ORDER BY timestamp "
    }
   ]
  }
 ]
}