$schema: https://schemas.meshmakers.cloud/construction-kit-elements.schema.json
enums:
  - enumId: ProductionType
    values:
      - key: 0
        name: Unknown
      - key: 1
        name: Solar
      - key: 2
        name: Water
      - key: 3
        name: Wind
      - key: 4
        name: Biomass